# Generated by Django 5.2.7 on 2025-12-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="user_type",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("STAFF", "Staff")],
                default="Staff",
                max_length=10,
            ),
        ),
    ]
